### ISSUE TITLE
[BUG] : Does not open UI on MacBook Air M1

### ISSUE THREAD

**Issue by tmxkn1** [Shabinder/SpotiFlyer#1872] opened 2022-10-17 15:46 UTC
**Describe the bug:**
The app does not run. No user interface is shown after double click the .jar file or launch from terminal.

**Expected behavior**
Launch a user interface

**StackTrace:**
```
%java --version
java 19 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)

% java -jar SpotiFlyer-macos-x64-3.6.2.jar
Debug: (Kermit) System Time:1666021241 , Token Expiry:1666024290
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQDxuThjYJd3jhAfeHkD7x0c2jHhqDfT1rB8yU8YKS_hFoUGUH90lT2RuKA7osuBH524UtHuhIKVm5MXlAdwZptk1CTs419yJKUZDCENhVd41sLMUyk, token_type=null, expiry=1666024290)
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
```

**Device Info (please complete the following information):**
 - Device:   MacBook Air M1 2020
 - OS:   MacOS
 - Version:   12.6
 - Country: Japan

**Comment by therealmichaelberna** [comment] 2022-10-20 05:52
Seems to be a duplicate of #1545

I'm experiencing the same issue on Windows 10 and java version 1.8.0_341

**Comment by therealmichaelberna** [comment] 2022-10-20 06:34
Hello guys, here's what I did that seems to have fixed it. Java changed up a bunch of things and now jars don't work with the old jre that we know and love. I had an older jre and a openjdk installed.
After installing jdk-19 from Java's website (they just call it "Java" now instead of jdk/jre), I set the %JAVA_HOME% variable and then re-launched it. It is working now for me at least.

**Comment by Shabinder** [comment] 2023-05-20 03:10
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Closed by Shabinder** 2023-05-20 03:10 UTC
Labels: bug
