### ISSUE TITLE
[BUG] : App becomes unresponsive at the setup screen

### ISSUE THREAD

**Issue by xnetcat** [Shabinder/SpotiFlyer#531] opened 2021-09-05 22:27 UTC
**Describe the bug**
App starts flickering and becomes unresponsive at the setup screen. It blocks me from using the home/back buttons. After restart it works as expected

**Media Links Used:** 
  - Irrelevant

**Expected behavior**
App would let me click the button and proceed with setup

**Screenshots**
https://user-images.githubusercontent.com/42355410/132142904-7e7b82fd-da6d-48e9-9030-7f936ab147ec.mp4

**StackTrace:**
I will try to get logs later this evening/tomorrow

**Device Info (please complete the following information):**
 - Device:   Xiaomi Redmi Note 9
 - OS:  Android
 - Version:   3.3.0

**Additional context**

**Comment by Shabinder** [comment] 2021-09-06 04:26
Hey @xnetcat, Thanks for reporting the issue and formating it so well.

The App behavior as shown is very strange and yes some Logs will be very helpful.
Just for the sake of clarification, flicker and unresponsiveness only happens on 1st Startup, But app works fine after that right ?

**Comment by xnetcat** [comment] 2021-09-06 04:50
@Shabinder 

> Just for the sake of clarification, flicker and unresponsiveness only happens on 1st Startup, But app works fine after that right ?

Correct

**Comment by xnetcat** [comment] 2021-09-06 05:13
Here are the logs:

[logs.txt](https://github.com/Shabinder/SpotiFlyer/files/7113474/logs.txt)

**Comment by xnetcat** [comment] 2021-09-06 05:28
More logs: [logcat_09-06-2021_07-27-27.txt](https://github.com/Shabinder/SpotiFlyer/files/7113521/logcat_09-06-2021_07-27-27.txt)

**Comment by Shabinder** [comment] 2021-09-06 05:41
From Logs It seems like **MIUI is giving some kind of issue** when app requests following permission
https://github.com/Shabinder/SpotiFlyer/blob/6fb1815252e70bfe77b27dbe579deeceafaa37f7/android/src/main/java/com/shabinder/spotiflyer/utils/UtilFunctions.kt#L65

And as of now App asks for this request **RECURSIVELY** Until Granted(I deemed it to be necessary as Background Downloads wont work in some devices then), hence causing flicker as App asks system to show Ignore Battery Optimization Dialog which system fails to do so, so app asks again and so on.........

**Expected Dialog:** 
![image](https://user-images.githubusercontent.com/44765050/132165790-42281738-e1da-43af-a74c-b971071a689f.png)

**Specifically at this point:**  https://github.com/Shabinder/SpotiFlyer/blob/6fb1815252e70bfe77b27dbe579deeceafaa37f7/android/src/main/java/com/shabinder/spotiflyer/MainActivity.kt#L411


**Loop as shown in logs:**
![image](https://user-images.githubusercontent.com/44765050/132165978-5284c19e-2b61-4ce0-9394-6e80bd76f226.png)
```
09-06 00:20:23.380  1365  2272 I ActivityTaskManager: START u0 {act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:com.shabinder.spotiflyer cmp=com.miui.powerkeeper/.ui.HiddenAppsConfigActivity} from uid 10360
09-06 00:20:23.398  1365  3150 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (930460)
09-06 00:20:23.400  1365  3150 W WindowManager: Changing focus fromWindow{e069c83 mode=1 rootTaskId=743 u0 com.shabinder.spotiflyer/com.shabinder.spotiflyer.MainActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6037 com.android.server.wm.DisplayContent.setFocusedApp:5723 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5694 
09-06 00:20:23.403  1365  3150 D WindowManager: Input focus has changed to null
09-06 00:20:23.406  1365  3150 I Timeline: Timeline: App_transition_ready time:930582
09-06 00:20:23.415  1365  2272 I Timeline: Timeline: App_transition_ready time:930591
09-06 00:20:23.421  1365  2272 I Timeline: Timeline: App_transition_ready time:930596
09-06 00:20:23.453  1365  2029 W WindowManager: Changing focus fromnull to Window{e069c83 mode=1 rootTaskId=743 u0 com.shabinder.spotiflyer/com.shabinder.spotiflyer.MainActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6037 com.android.server.wm.DisplayContent.setFocusedApp:5723 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5694 
09-06 00:20:23.455  1365  2029 D WindowManager: Input focus has changed to Window{e069c83 mode=1 rootTaskId=743 u0 com.shabinder.spotiflyer/com.shabinder.spotiflyer.MainActivity}
09-06 00:20:23.459 24505 24505 I Timeline: Timeline: Activity_launch_request time:930634
09-06 00:20:23.467  1365  2029 I Timeline: Timeline: App_transition_ready time:930642
09-06 00:20:23.467  1365  2029 I Timeline: Timeline: App_transition_stopped time:930643
```


**Expected Whole Flow Screen Record:**
https://user-images.githubusercontent.com/44765050/132165870-f0fc8270-d5f7-4abf-883f-332b346686d8.mp4

**Comment by xnetcat** [comment] 2021-09-06 07:10
https://stackoverflow.com/questions/68305845/ignore-battery-optimization-permission-for-our-android-app-is-getting-denied-on

Looks like there is no way around this

**Comment by Shabinder** [comment] 2021-09-06 09:22
> 
> 
> https://stackoverflow.com/questions/68305845/ignore-battery-optimization-permission-for-our-android-app-is-getting-denied-on
> 
> Looks like there is no way around this

so MIUI is at fault here I guess...
Is this a major issue for you @xnetcat ? like just closing the app once and then everything is normal right...?

If this effect can be endured, I am more inclined toward marking this as **wontfix** as the issue isn't at the app's side and keeping ignore-battery-optimizations is still a **Necessary Requirement** and I don't plan to give here a choice as if I do then some users will deny background permission and then report an error about the app not downloading.

However, I am open to your suggestions.

**Comment by xnetcat** [comment] 2021-09-06 09:27
> > 
> > 
> > https://stackoverflow.com/questions/68305845/ignore-battery-optimization-permission-for-our-android-app-is-getting-denied-on
> > 
> > Looks like there is no way around this
> 
> so MIUI is at fault here I guess...
> Is this a major issue for you @xnetcat ? like just closing the app once and then everything is normal right...?
> 
> If this effect can be endured, I am more inclined toward marking this as **wontfix** as the issue isn't at the app's side and keeping ignore-battery-optimizations is still a **Necessary Requirement** and I don't plan to give here a choice as if I do then some users will deny background permission and then report an error about the app not downloading.
> 
> However, I am open to your suggestions.

After reopening the app everything works as expected, not sure if battery optimization confirmation is required on MIUI as it uses some custom battery optimization technique by default (pic attached).

Maybe just don't show the dialog on MIUI with android 11

**Comment by Shabinder** [comment] 2023-05-20 14:55
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Closed by Shabinder** 2023-05-20 14:55 UTC
Labels: bug
