### ISSUE TITLE
Download wrong song

### ISSUE THREAD

**Issue by MikeCant0** [Shabinder/SpotiFlyer#186] opened 2021-06-25 06:05 UTC
Sometimes the app download another version of the app or a different song.  Still it's not tahn important,  I only got tahr error in 2 song out of 600. It's funny really,  one time instead of downloading a Calvin Harris song it downloaded a instrumental song with the name of Calvin's one. In helps me to discover random music.  And thank you very much for this awesome project, I am will give you a coffee (wish I can give you more)

**Comment by Shabinder** [comment] 2021-06-25 07:15
I am glad you like this project and **I appreciate** any kind of support you give :smiley: 

I am aware that the songs are not matched with 100 % accuracy, its kinda **feature in disguise as a Bug** :upside_down_face: 

However drop the song/ playlist link down,  where you faced the wrong song error , So when I work on enhancing the matching algo , I can take a look and verify if changes will improve matching or not...

**Comment by alexanderadam** [comment] 2021-06-27 10:11
Duplicate of #145

**Closed** 2021-09-05 17:31 UTC
Labels: match-error
