### ISSUE TITLE
No song download

### ISSUE THREAD

**Issue by itsddpanda** [Shabinder/SpotiFlyer#27] opened 2020-12-05 15:21 UTC
It just keeps spinning and does not download the songs.
I used playlist from spotify and then download all option.

**Comment by Shabinder** [comment] 2020-12-05 21:01
ShareYour Device Info Please.

**Comment by MalusiMbatha** [comment] 2020-12-07 13:09
On my phone too its does the same thing i was using version 1.5 1 and it was working fine until i updated to 1.8 then it does not download it only circulates and downloads nothing,i am using samsung galaxy A30s

**Comment by vinch49** [comment] 2020-12-07 14:36
It's the same for me. Release 1.6 is good but not 1.8...
thanks for development

**Comment by vinch49** [comment] 2020-12-08 08:16
Hi, many thks for new release but it's not working on my phone . it's same problem with 1.8 & 1.7
I upgrade on #1.6.

Pocophone F1 - MIUI 11.0.8

**Comment by Shabinder** [comment] 2020-12-08 09:32
> Hi, many thks for new release but it's not working on my phone . it's same problem with 1.8 & 1.7
Yes I have Been Notified About the issue , but I am not able to reproduce it on my end.
I will fix the issue as soon as I get My hand on another device with this Issue.

**Comment by Shabinder** [comment] 2021-01-03 17:30
Fixed in v2.0 release.

**Closed by Shabinder** 2021-01-03 17:30 UTC
Labels: bug
