### ISSUE TITLE
no option to download in 320kbps download only in 128kbps

### ISSUE THREAD

**Issue by rohitprasadopenxcell** [Shabinder/SpotiFlyer#59] opened 2021-03-09 06:38 UTC

**Comment by Shabinder** [comment] 2021-03-09 07:47
Duplicate of #47 ,
I am sorry to inform but 320kbps is not available from youtube.

**Closed by Shabinder** 2021-03-09 07:47 UTC

**Comment by Peouyb** [comment] 2021-06-23 02:22
Download spotify

**Comment by Peouyb** [comment] 2021-06-23 02:23
[NUEVOS ARLS 17 DE ABRIL.txt](https://github.com/Shabinder/SpotiFlyer/files/6698456/NUEVOS.ARLS.17.DE.ABRIL.txt)

**Comment by Towhidul1** [comment] 2021-07-02 12:21
Only loading
Download not working
