### ISSUE TITLE
[BUG] : Low resolution Album cover and YouTube Shorts link not working. 

### ISSUE THREAD

**Issue by nikhiljanu2004** [Shabinder/SpotiFlyer#1870] opened 2022-10-17 10:02 UTC
<!---

**Describe the bug:**
Spotify links work very well and the album covers were clear till the last version(3.6.1) this new version(3.6.2) downloads a very low-resolution album cover. And In the previous versions, YouTube Shorts links do work well, but this version(3.6.2) is not supporting them. 

**Media Links Used:** 
https://open.spotify.com/track/3GaeH4EFwtkY2IJfs85u8u?si=zOP_C8IyRcWNgQYLhK_oxQ&utm_source=copy-link

**Expected behavior**
![Screenshot_20221017-150730_Samsung Music.jpg](https://user-images.githubusercontent.com/115984811/196144239-9e7909ed-cd1e-4984-bc56-c9c1045dbaf9.jpg)

**Screenshots:**
![Screenshot_20221017-150832.jpg](https://user-images.githubusercontent.com/115984811/196144479-f3808c62-4b88-4969-a2df-d463ec4ce897.jpg)

**Device Info (please complete the following information):**
 - Device: Samsung J6 Infinity
 - OS:   Android 10
 - Version:   3.6.1
 - Country: India

**Additional context:**
The screenshots I pasted are for comparison, I downloaded this song a month ago, and now the album cover is blurry.

**Comment by d4f5409d** [comment] 2022-10-18 20:51
Duplicate of #1868

**Comment by Shabinder** [comment] 2022-10-24 14:06
Fixed in v3.6.3.

**Closed by Shabinder** 2022-10-24 14:06 UTC
Labels: bug
