### ISSUE TITLE
Seems like all of us have the same issue. We couldn't download.

For my instance, I could download at home while using wifi but, now when I am outside using my cellular data, I can't download music. Maybe the issue is because the app is not compatible with cellular data downloading. 

### ISSUE THREAD

**Issue by hasa12977** [Shabinder/SpotiFlyer#949] opened 2022-01-22 23:07 UTC

**Comment by yavnaz** [comment] 2022-01-23 18:52
I can download on soundcloud, using cellular. The problem is with spotify & youtube

**Comment by Shabinder** [comment] 2022-01-26 21:11
Fixed in **v3.6.0** : https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.6.0

**Closed by Shabinder** 2022-01-26 21:11 UTC
