### ISSUE TITLE
Music player doesn't always show songs after download

### ISSUE THREAD

**Issue by Bwangster12** [Shabinder/SpotiFlyer#16] opened 2020-11-26 23:37 UTC
I have an LG phone and the stock music player doesn't seem to recognize the songs after they've been downloaded.  I went to the Google File Manager and the files weren't recognized under audio either.  I went into the Music folder and found the Spotiflyer folder and the songs played through the file manager.  Not sure what the issue was.

**Comment by Shabinder** [comment] 2020-11-27 03:27
the issue is your Media Library wasnt updated , you can update it through your media app if it provides a refresh like button(for instance : poweramp does).
However a restart will also update it,(but i will probably fix this in upcoming release. **_Stay Tuned_**)

**Comment by Shabinder** [comment] 2020-12-02 16:36
Fixed in New Update v1.7.
After each song Download , It is Added to Android Media Store _(i.e.,Library)_

**Closed by Shabinder** 2020-12-02 16:36 UTC
